#!/bin/bash

# macOS Settings
SHOW_HIDDEN_FILES=true
SHOW_STATUS_BAR=true
SHOW_PATH_BAR=true
KEEP_FOLDERS_ON_TOP=true
DISABLE_AUTO_CORRECT=false
ENABLE_TAP_TO_CLICK=true
KEY_REPEAT_RATE=2
INITIAL_KEY_REPEAT=15
FINDER_VIEW_STYLE="Nlsv"
DISABLE_EXTENSION_CHANGE_WARNING=true
AVOID_DS_STORE_ON_NETWORK=true
AVOID_DS_STORE_ON_USB=true
DISABLE_OPEN_APP_PROMPT=false

# Set Arc as default browser
SET_ARC_AS_DEFAULT_BROWSER=true
